"""virtual_casing_jax package."""

from . import surface_ops
from .surface_ops import (
    complete_vec_field,
    rotate_toroidal,
    upsample,
    resample,
    grad2d,
    surf_normal_area_elem,
    dot_prod,
    cross_prod,
    normal_orientation,
)
from .kernels import (
    laplace_fx_u,
    laplace_fxd_u,
    laplace_fxd2_u,
    laplace_dx_u,
    biotsavart_fx_u,
    biotsavart_fxd_u,
)
from .integrals import (
    laplace_fxd_u_eval,
    laplace_fxd_u_eval_vec,
    laplace_fxd_u_eval_singular,
    laplace_fxd_u_eval_vec_singular,
    laplace_fxd2_u_eval,
    laplace_fxd2_u_eval_vec,
    laplace_fxd2_u_eval_singular,
    laplace_fxd2_u_eval_vec_singular,
    field_period_target_coords,
    biotsavart_fx_u_eval,
    laplace_dx_u_eval,
    computeB_offsurface_baseline,
    computeB_offsurface_adaptive,
    computeB_offsurface_adaptive_schedule,
    computeGradB_offsurface_adaptive_schedule,
    laplace_dx_u_eval_singular,
)
from .virtual_casing import VirtualCasingJAX
from . import functional
from .functional import (
    FunctionalSetup,
    build_surface_coord,
    build_quad_setup,
    build_patch_idx,
    select_patch_dim_from_geom,
    prepare_functional_setup,
    compute_external_B_functional,
    compute_internal_B_functional,
    compute_external_gradB_functional,
    compute_internal_gradB_functional,
    compute_external_B_offsurf_functional,
    compute_external_gradB_offsurf_functional,
)
from . import singular_quadrature

__all__ = [
    "surface_ops",
    "complete_vec_field",
    "rotate_toroidal",
    "upsample",
    "resample",
    "grad2d",
    "surf_normal_area_elem",
    "dot_prod",
    "cross_prod",
    "normal_orientation",
    "laplace_fx_u",
    "laplace_fxd_u",
    "laplace_fxd2_u",
    "laplace_dx_u",
    "biotsavart_fx_u",
    "biotsavart_fxd_u",
    "laplace_fxd_u_eval",
    "laplace_fxd_u_eval_vec",
    "laplace_fxd_u_eval_singular",
    "laplace_fxd_u_eval_vec_singular",
    "laplace_fxd2_u_eval",
    "laplace_fxd2_u_eval_vec",
    "laplace_fxd2_u_eval_singular",
    "laplace_fxd2_u_eval_vec_singular",
    "field_period_target_coords",
    "biotsavart_fx_u_eval",
    "laplace_dx_u_eval",
    "computeB_offsurface_baseline",
    "computeB_offsurface_adaptive",
    "computeB_offsurface_adaptive_schedule",
    "computeGradB_offsurface_adaptive_schedule",
    "laplace_dx_u_eval_singular",
    "VirtualCasingJAX",
    "functional",
    "FunctionalSetup",
    "build_surface_coord",
    "build_quad_setup",
    "build_patch_idx",
    "select_patch_dim_from_geom",
    "prepare_functional_setup",
    "compute_external_B_functional",
    "compute_internal_B_functional",
    "compute_external_gradB_functional",
    "compute_internal_gradB_functional",
    "compute_external_B_offsurf_functional",
    "compute_external_gradB_offsurf_functional",
    "singular_quadrature",
]
