"""virtual_casing_jax package."""

from . import surface_ops
from .surface_ops import (
    complete_vec_field,
    rotate_toroidal,
    upsample,
    resample,
    grad2d,
    surf_normal_area_elem,
    dot_prod,
    cross_prod,
    normal_orientation,
)
from .kernels import (
    laplace_fx_u,
    laplace_fxd_u,
    laplace_fxd2_u,
    laplace_dx_u,
    biotsavart_fx_u,
    biotsavart_fxd_u,
)
from .integrals import (
    laplace_fxd_u_eval,
    laplace_fxd_u_eval_vec,
    laplace_fxd_u_eval_singular,
    laplace_fxd_u_eval_vec_singular,
    laplace_fxd2_u_eval,
    laplace_fxd2_u_eval_vec,
    laplace_fxd2_u_eval_singular,
    laplace_fxd2_u_eval_vec_singular,
    field_period_target_coords,
    biotsavart_fx_u_eval,
    laplace_dx_u_eval,
    computeB_offsurface_baseline,
    computeB_offsurface_adaptive,
)
from . import singular_quadrature

__all__ = [
    "surface_ops",
    "complete_vec_field",
    "rotate_toroidal",
    "upsample",
    "resample",
    "grad2d",
    "surf_normal_area_elem",
    "dot_prod",
    "cross_prod",
    "normal_orientation",
    "laplace_fx_u",
    "laplace_fxd_u",
    "laplace_fxd2_u",
    "laplace_dx_u",
    "biotsavart_fx_u",
    "biotsavart_fxd_u",
    "laplace_fxd_u_eval",
    "laplace_fxd_u_eval_vec",
    "laplace_fxd_u_eval_singular",
    "laplace_fxd_u_eval_vec_singular",
    "laplace_fxd2_u_eval",
    "laplace_fxd2_u_eval_vec",
    "laplace_fxd2_u_eval_singular",
    "laplace_fxd2_u_eval_vec_singular",
    "field_period_target_coords",
    "biotsavart_fx_u_eval",
    "laplace_dx_u_eval",
    "computeB_offsurface_baseline",
    "computeB_offsurface_adaptive",
    "singular_quadrature",
]
